### PR TITLE
support some pep517 build backends

### PR DESCRIPTION
**Pull request by emmettbutler**
* Adds support for the `hatchling` and `flit_core` PEP517 build backends
* Fixes an infinite recursion bug by avoiding package name collisions in overlay
* Adds a `--py` argument to the CLI allowing the user to specify the Python version to be used in the built shell
* Pins nixpkgs to improve reproducibility

### CODE REVIEW

**Comment by cript0nauta** [comment]
> Pins nixpkgs to improve reproducibility

I think [this change](https://github.com/cript0nauta/pynixify/pull/64/commits/b15cc06faaef075eca7d5f9a3e677b610b942221) shouldn't be necessary. If you use the `--nixpkgs` option, the expression will be instantiated with `<nixpkgs>` pinned to the desired version: https://github.com/cript0nauta/pynixify/blob/main/pynixify/nixpkgs_sources.py#L135

**Comment by cript0nauta** [comment]
`Adds a --py argument to the CLI allowing the user to specify the Python version to be used in the built shell`

This change looks good. Would you be able to create a new PR that only includes this fix, without any changes to formatting or import order?

Also, please make sure to use the [`escape_string`](https://github.com/cript0nauta/pynixify/blob/main/pynixify/expression_builder.py#L227) function when including a string inside a Nix expression.

**Comment by cript0nauta** [comment]
> Fixes an infinite recursion bug by avoiding package name collisions in overlay

Do you have an example of when this bug is triggered? Maybe we should create a test in the [command test suite](https://github.com/cript0nauta/pynixify/blob/main/acceptance_tests/test_command.sh) that reproduces it.

**Comment by cript0nauta** [comment]
> Adds support for the hatchling and flit_core PEP517 build backends

This changeset looks interesting, though I'm not familiar with PEP517. I'll need some time to review the changes since they're larger than the other fixes.

Thanks again for your contributions!

**Comment by emmettbutler** [comment]
@cript0nauta thanks for the quick feedback! i broke out the pep517 changes into this pull request for your review https://github.com/cript0nauta/pynixify/pull/65

other broken-out pull requests are forthcoming.

**Pull request closed without merging**
